### ISSUE TITLE
Uncaught ReferenceError: error is not defined

### ISSUE THREAD

**Issue by rwuttke** [TOP-Chao/atom-react-native-css#11]
1. ...Upgade from 1.6.0 to 1.7.1 of Atom
2. ...Start Atom

**Atom Version**: 1.7.1
**System**: Microsoft Windows 10 Home
**Thrown From**: [atom-react-native-css](https://github.com/TOP-Chao/atom-react-native-css) package, v1.0.0
### Stack Trace

Uncaught ReferenceError: error is not defined

```
At C:\Users\Robert Wuttke\.atom\packages\atom-react-native-css\lib\index.js:129

ReferenceError: error is not defined
    at Object.error (C:\Users\Robert Wuttke\.atom\packages\atom-react-native-css\lib\index.js:129:29)
    at exec (C:\Users\Robert Wuttke\.atom\packages\atom-react-native-css\lib\index.js:152:30)
    at exithandler (child_process.js:232:5)
    at ChildProcess.errorhandler (child_process.js:244:5)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "nuclide"
    ],
    "projectHome": "E:\\git",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "atom-react-native-css": {
    "enableSass": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-react-native-autocomplete, v0.0.7
atom-react-native-css, v1.0.0
browser-plus, v0.0.60
color-picker, v2.1.1
file-icons, v1.7.1
format-graphql, v0.1.2
formatter-coffeescript, v0.1.1
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
jquery-snippets, v11.0.0
language-babel, v2.17.1
language-batch, v0.3.3
language-gradle, v0.0.3
language-graphql, v0.2.0
language-ini, v1.16.0
language-javascript-jsx, v0.3.7
language-jison, v2.2.0
language-ocaml, v1.1.2
language-swift, v0.4.0
language-thrift, v1.0.2
linter, v1.11.4
meteor-api, v2.20.0
minimap, v4.21.0
minimap-git-diff, v4.2.0
navigate, v0.1.15
node_modules, vundefined
react, v0.15.0
react-snippets, v0.4.2
Stylus, v3.0.0
terminal-plus, v0.14.5
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by 94cstyles** [comment]
The problem has been resolved, please update to the latest version.

**Comment by rwuttke** [comment]
Thanks will do.
