### ISSUE TITLE
Failed to load the atom-react-native-css package

### ISSUE THREAD

**Issue by xubing** [TOP-Chao/atom-react-native-css#13]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-react-native-css](https://github.com/TOP-Chao/atom-react-native-css) package, v0.0.4
### Stack Trace

Failed to load the atom-react-native-css package

```
At The `libsass` binding was not found in /Users/Bing/.atom/packages/atom-react-native-css/node_modules/node-sass/vendor/darwin-x64-47/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.

Error: The `libsass` binding was not found in /Users/Bing/.atom/packages/atom-react-native-css/node_modules/node-sass/vendor/darwin-x64-47/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/Users/Bing/.atom/packages/atom-react-native-css/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/Users/Bing/.atom/packages/atom-react-native-css/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Bing/.atom/packages/atom-react-native-css/lib/compile.js:7:12)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Bing/.atom/packages/atom-react-native-css/lib/index.js:5:15)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Quick-JavaScript, v0.11.0
atom-ctags, v4.5.0
atom-react-native-autocomplete, v0.0.5
atom-react-native-css, v0.0.4
atom-ternjs, v0.13.2
autocomplete-ctags, v0.4.0
autocomplete-emp-lua, v0.8.0
color-picker, v2.1.1
language-javascript-jsx, v0.3.7
language-lua, v0.9.4
minimap, v4.21.0
react-es6-snippets, v0.3.0
react-snippets, v0.3.0

# Dev
No dev packages
```

**Comment by 94cstyles** [comment]
[look here](https://github.com/TOP-Chao/atom-react-native-css#file-support)
