### ISSUE TITLE
Uncaught Error: Missing binding $ATOM_HOME/packages/atom-react-native-css/node_modules/node-sass/...

### ISSUE THREAD

**Issue by dajwill** [TOP-Chao/atom-react-native-css#15]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-react-native-css](https://github.com/TOP-Chao/atom-react-native-css) package, v1.1.0
### Stack Trace

Uncaught Error: Missing binding /Users/cestaff/.atom/packages/atom-react-native-css/node_modules/node-sass/vendor/darwin-x64-47/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 5.x

Found bindings for the following environments:
- OS X 64-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.

```
At /Users/cestaff/.atom/packages/atom-react-native-css/node_modules/node-sass/lib/index.js:14

Error: Missing binding /Users/cestaff/.atom/packages/atom-react-native-css/node_modules/node-sass/vendor/darwin-x64-47/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 5.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (/Users/cestaff/.atom/packages/atom-react-native-css/node_modules/node-sass/lib/index.js:14:11)
    at Module._compile (/Users/cestaff/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/cestaff/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/cestaff/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at compile.parseJSS (/Users/cestaff/.atom/packages/atom-react-native-css/lib/compile.js:79:77)
    at /Users/cestaff/.atom/packages/atom-react-native-css/lib/index.js:106:13
```
### Commands

```
     -4:12.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:11.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:11.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -4:08.2.0 core:save (atom-text-editor.editor.is-focused)
     -3:51.9.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -3:51.1.0 core:save (atom-text-editor.editor.is-focused)
     -3:17.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:18.2.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  2x -0:17 core:save (atom-text-editor.editor.is-focused)
     -0:11.9.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  2x -0:11.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "atom-react-native-css": {
    "enableSass": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-jade, v0.3.0
atom-react-native-css, v1.1.0
autoclose-html, v0.18.0
language-haml, v0.23.15
language-vue, v0.11.0
linter-ruby, v1.0.2

# Dev
No dev packages
```

**Comment by 94cstyles** [comment]
[download file](https://github.com/sass/node-sass/releases/download/v3.7.0/darwin-x64-47_binding.node)

**Comment by lobinfeng** [comment]
安装一下node-sass包
