### ISSUE TITLE
Uncaught Error: Missing binding /Volumes/Macintosh HD/Dropbox/Apps/atom/packages/atom-react-nativ...

### ISSUE THREAD

**Issue by beijipc** [TOP-Chao/atom-react-native-css#16]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-react-native-css](https://github.com/TOP-Chao/atom-react-native-css) package, v1.1.0
### Stack Trace

Uncaught Error: Missing binding /Volumes/Macintosh HD/Dropbox/Apps/atom/packages/atom-react-native-css/node_modules/node-sass/vendor/darwin-x64-47/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 5.x

Found bindings for the following environments:
- OS X 64-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.

```
At /Volumes/Macintosh HD/Dropbox/Apps/atom/packages/atom-react-native-css/node_modules/node-sass/lib/index.js:14

Error: Missing binding /Volumes/Macintosh HD/Dropbox/Apps/atom/packages/atom-react-native-css/node_modules/node-sass/vendor/darwin-x64-47/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 5.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (/Volumes/Macintosh HD/Dropbox/Apps/atom/packages/atom-react-native-css/node_modules/node-sass/lib/index.js:14:11)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at compile.parseJSS (/Volumes/Macintosh HD/Dropbox/Apps/atom/packages/atom-react-native-css/lib/compile.js:79:77)
    at /Volumes/Macintosh HD/Dropbox/Apps/atom/packages/atom-react-native-css/lib/index.js:106:13
```
### Commands

```
     -0:06.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.2.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-terminal",
      "autocomplete-wordpress-hooks",
      "language-javascript-jsx",
      "react-snippets",
      "angularjs",
      "angularjs-snippets",
      "atom-ng-attr-hint",
      "react",
      "terminal-panel",
      "language-prolog"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "atom-react-native-css": {
    "enableSass": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.7
atom-jade, v0.3.0
atom-less, v0.1.10
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.11
atom-react-native-autocomplete, v0.0.24
atom-react-native-css, v1.1.0
atom-xcode, v0.1.3
autocomplete-paths, v1.0.2
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.11
flex-tool-bar, v0.10.0
jade-autocompile, v0.8.3
jquery-snippets, v11.0.0
jslint, v1.5.1
language-babel, v2.20.10
markdown-preview-plus, v2.4.0
minimap, v4.23.5
minimap-find-and-replace, v4.5.1
pigments, v0.26.3
project-manager, v2.9.7
simplified-chinese-menu, v3.4.11
source-preview-jade, v0.1.1
source-preview-pug, v0.2.0
tool-bar, v0.4.0
tool-bar-main, v0.0.9
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by 94cstyles** [comment]
这种通常发生在nodejs版本变更的情况下，进入插件目录执行命令`npm rebuild node-sass`。如果还不行 卸载插件重新安装，最后还是不行，那么只能放弃使用sass方案，这是由[node-sass](https://github.com/sass/node-sass)开发，你可以去[issues](https://github.com/sass/node-sass/issues)寻求解决方案。

**Comment by beijipc** [comment]
问题的根源好象是atom-react-native-css安装的drawin-x64-46版本，而node-sass却在找darwin-x64-47。所以报错。

**Comment by 94cstyles** [comment]
你去[node-sass](https://github.com/sass/node-sass/releases) 下载缺失的文件。
你这么理解有点问题，插件安装的版本是`node-sass`自己下载的，但是它最终找的也是自己搞的，反正经常出现这个问题，这种问题基本上都是更改过Node版本，导致node-sass依赖的文件发生了变化。

**Comment by beijipc** [comment]
是的，下载了darwin-x64-47问题解决。
