### ISSUE TITLE
Uncaught Error: undefined:2945:6: property missing ':'

### ISSUE THREAD

**Issue by elhombreforestal** [TOP-Chao/atom-react-native-css#23]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [atom-react-native-css](https://github.com/TOP-Chao/atom-react-native-css) package, v1.1.2
### Stack Trace

Uncaught Error: undefined:2945:6: property missing ':'

```
At /home/daniel/.atom/packages/atom-react-native-css/node_modules/css/lib/parse/index.js:72

Error: undefined:2945:6: property missing ':'
    at error (/home/daniel/.atom/packages/atom-react-native-css/node_modules/css/lib/parse/index.js:62:15)
    at declaration (/home/daniel/.atom/packages/atom-react-native-css/node_modules/css/lib/parse/index.js:223:33)
    at declarations (/home/daniel/.atom/packages/atom-react-native-css/node_modules/css/lib/parse/index.js:252:19)
    at rule (/home/daniel/.atom/packages/atom-react-native-css/node_modules/css/lib/parse/index.js:560:21)
    at rules (/home/daniel/.atom/packages/atom-react-native-css/node_modules/css/lib/parse/index.js:117:70)
    at atmedia (/home/daniel/.atom/packages/atom-react-native-css/node_modules/css/lib/parse/index.js:380:35)
    at atrule (/home/daniel/.atom/packages/atom-react-native-css/node_modules/css/lib/parse/index.js:534:10)
    at rules (/home/daniel/.atom/packages/atom-react-native-css/node_modules/css/lib/parse/index.js:117:58)
    at stylesheet (/home/daniel/.atom/packages/atom-react-native-css/node_modules/css/lib/parse/index.js:81:21)
    at Object.module.exports [as parse] (/home/daniel/.atom/packages/atom-react-native-css/node_modules/css/lib/parse/index.js:564:20)
    at Object.module.exports.refreshWordList (/home/daniel/.atom/packages/css-spy/lib/provider.coffee:45:25)
    at FSWatcher.<anonymous> (/home/daniel/.atom/packages/css-spy/lib/css-spy.coffee:34:22)
    at emitTwo (events.js:87:13)
    at FSWatcher.emit (events.js:172:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1310:12)
```
### Commands

```
     -1:13.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  3x -1:13.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:11.2.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
 10x -1:02.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:53.1.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:52.1.0 core:delete (atom-text-editor.editor.is-focused)
     -0:51.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  4x -0:51.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:50.7.0 core:delete (atom-text-editor.editor.is-focused)
     -0:50.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:29.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:24.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:22.9.0 core:delete (atom-text-editor.editor.is-focused)
  2x -0:22.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:01.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.8
atom-react-native-css, v1.1.2
autoclose-html, v0.23.0
css-comb, v2.4.3
css-spy, v0.5.1
editorconfig, v1.4.1
highlight-selected, v0.11.2
hyperclick, v0.0.36
js-hyperclick, v1.4.2
jsformat, v0.9.3
language-babel, v2.28.0
language-slim, v0.5.0
linter, v1.11.10
linter-eslint, v7.2.2
linter-flow, v5.4.0
merge-conflicts, v1.4.4
minimap, v4.24.6
minimap-highlight-selected, v4.4.0
pigments, v0.29.2
react, v0.15.0

# Dev
No dev packages
```

**Comment by 94cstyles** [comment]
please reinstall. `css` module installation problems.
