### ISSUE TITLE
Uncaught Error: fontWeight value in ["normal", "bold", "100", "200", "300", "400", "500", "600", ...

### ISSUE THREAD

**Issue by jussielo** [TOP-Chao/atom-react-native-css#24]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-react-native-css](https://github.com/TOP-Chao/atom-react-native-css) package, v1.1.2
### Stack Trace

Uncaught Error: fontWeight value in ["normal", "bold", "100", "200", "300", "400", "500", "600", "700", "800", "900"]

```
At /Users/jussielo/.atom/packages/atom-react-native-css/lib/compile.js:78

Error: fontWeight value in ["normal", "bold", "100", "200", "300", "400", "500", "600", "700", "800", "900"]
    at Object.compile.formatJSS (/Users/jussielo/.atom/packages/atom-react-native-css/lib/compile.js:78:23)
    at /Users/jussielo/.atom/packages/atom-react-native-css/lib/compile.js:110:37
    at Array.forEach (native)
    at /Users/jussielo/.atom/packages/atom-react-native-css/lib/compile.js:108:43
    at Array.forEach (native)
    at /Users/jussielo/.atom/packages/atom-react-native-css/lib/compile.js:104:36
    at Array.forEach (native)
    at compile.parseJSS (/Users/jussielo/.atom/packages/atom-react-native-css/lib/compile.js:101:43)
    at /Users/jussielo/.atom/packages/atom-react-native-css/lib/index.js:106:13
```
### Commands

```
     -4:19.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -4:05.6.0 core:save (atom-text-editor.editor.is-focused)
     -4:05.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:05.0 core:cancel (atom-text-editor.editor.is-focused)
     -4:03.1.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -4:00.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:00.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:59 find-and-replace:show (atom-text-editor.editor.is-focused)
     -3:58 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:56.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -3:55.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:55.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:24.5.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
  3x -0:07.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:02.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.9.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, vundefined
atom-minify, v0.7.5
atom-react-native-autocomplete, v0.0.27
atom-react-native-css, v1.1.2
auto-detect-indentation, v1.1.0
autoclose-html, v0.23.0
autocomplete-php, v0.3.7
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.15
highlight-selected, v0.11.2
language-javascript-jsx, v0.3.7
linter, v1.11.14
minimap, v4.24.6
open-recent, v5.0.0
php-cs-fixer, v2.5.6
pigments, v0.29.3
project-manager, v2.9.7
save-session, v0.16.0

# Dev
No dev packages
```

**Comment by 94cstyles** [comment]
``` css
font-weight: "300";
or
font-weight: 300;
```

value in ["normal", "bold", "100", "200", "300", "400", "500", "600", "700", "800", "900"]

**Comment by Kosai106** [comment]
I just experienced this as well - Turns out it doesn't like it if you add `!important` after the value. Or rather, that's what it seems like.

**Comment by tayler-king** [comment]
I've been receiving this for weeks.. It's really annoying.

**Comment by kevnk** [comment]
I'm still getting this error today.

```
$ yarn add bootstrap@4.0.0-alpha.6
```

Then in app.scss:

```
@import "node_modules/bootstrap/scss/bootstrap.scss";
```

Getting error:

```
Uncaught Error: fontWeight value in ["normal", "bold", "100", "200", "300", "400", "500", "600", "700", "800", "900"]
```
