### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/work/projects/code/sso/app/assets/styl...

### ISSUE THREAD

**Issue by ram-ai-kumar** [TOP-Chao/atom-react-native-css#36]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-react-native-css](https://github.com/TOP-Chao/atom-react-native-css) package 1.1.3

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/ram/work/projects/code/sso/app/assets/stylesheets/application.css'

```
At fs.js:640

Error: ENOENT: no such file or directory, open '/Users/ram/work/projects/code/sso/app/assets/stylesheets/application.css'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at Object.parseCSS (/packages/atom-react-native-css/lib/compile.js:90:28)
    at /packages/atom-react-native-css/lib/index.js:121:23
```

### Commands

```
     -3:53.5.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -3:53.2.0 core:move-left (input.hidden-input)
  4x -3:52.8.0 core:select-left (input.hidden-input)
     -3:14.8.0 core:paste (input.hidden-input)
     -3:14.3.0 core:save (input.hidden-input)
     -1:16.8.0 find-and-replace:show (input.hidden-input)
     -1:15.2.0 core:confirm (input.hidden-input)
     -1:14.3.0 editor:consolidate-selections (input.hidden-input)
     -1:14.3.0 core:cancel (input.hidden-input)
     -1:13.8.0 editor:consolidate-selections (input.hidden-input)
     -1:13.8.0 core:cancel (input.hidden-input)
     -0:45 tree-view:move (span.name.icon.css3-icon.medium-blue)
     -0:36.5.0 core:confirm (input.hidden-input)
     -0:22.4.0 core:paste (input.hidden-input)
     -0:19.8.0 editor:newline (input.hidden-input)
     -0:16 core:save (input.hidden-input)
```

### Non-Core Packages

```
align-by 0.1.0 
atom-beautify 0.29.17 
atom-material-syntax 1.0.2 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
atom-react-native-autocomplete 0.0.27 
atom-react-native-css 1.1.3 
atom-react-preview 2.0.0 
color-picker 2.2.5 
copy-as-rtf 0.9.3 
emmet 2.4.3 
file-icons 2.0.16 
gist-it 0.9.2 
language-javascript-jsx 0.3.7 
lcov-info 0.12.0 
linter 1.11.23 
linter-rubocop 0.5.3 
pigments 0.39.0 
project-manager 3.3.3 
rails-partials 0.9.2 
rails-snippets 2.12.0 
react 0.16.2 
react-es6-snippets 0.3.0 
react-snippets 0.7.0 
ruby-syntax-replacer 0.5.1 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.3 
toggle-quotes 1.0.0 
```

**Comment by 94cstyles** [comment]
I'm sorry, the project has stopped maintenance.
