### ISSUE TITLE
Failed to activate the atom-react-native-css package

### ISSUE THREAD

**Issue by b82** [TOP-Chao/atom-react-native-css#5]
I've tried to update my packagr from Atom editor then I've got this error

**Atom Version**: 1.6.0
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-react-native-css](https://github.com/TOP-Chao/atom-react-native-css) package, v0.0.5
### Stack Trace

Failed to activate the atom-react-native-css package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.activate (/Users/b/.atom/packages/atom-react-native-css/lib/index.js:64:9)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -6:06.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -6:05.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -5:59.4.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:34.8.0 core:copy (atom-text-editor.editor.is-focused)
     -2:16.8.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -2:16.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:15.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:12.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -2:12.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:08.1.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:49 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -1:47.2.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:44.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:44.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:14.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-react-native-autocomplete, v0.0.6
atom-react-native-css, v0.0.5
color-picker, v2.1.1
emmet, v2.4.3
language-babel, v2.16.0
language-javascript-jsx, v0.3.7
react, v0.14.2

# Dev
No dev packages
```

**Comment by 94cstyles** [comment]
#3
